sonar.projectKey=ChipanaFadiley_ucv-ate-si-lab05
sonar.organization=chipanaadiley

# This is the name displayed in the SonarQube Cloud UI.
sonar.projectName=ucv-ate-si-lab05

# Path is relative to the sonar-project.properties file.
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,.venv/**,.pytest_cache/**,data/**
sonar.test.inclusions=tests/**/*.py
