sonar.projectKey=ucv-ate-si-lab05
sonar.projectName=ucv-ate-si-lab05
sonar.organization=ucv-ate-si-lab05
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
