name: Analisis con SonarCloud

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  sonarcloud:
    name: Pruebas y analisis
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        run: pipx install poetry

      - name: Configurar entorno de Poetry
        run: poetry config virtualenvs.in-project true

      - name: Instalar dependencias
        run: poetry install

      - name: Ejecutar pruebas con cobertura
        run: poetry run pytest

      - name: Analizar en SonarCloud
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
